name: Greeting Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Greet user
        run: echo "Hello, ${{ github.actor }}!"